title: Dog Breeds Classifier
description: Classify dog breeds using deep learning
about:
  This is a dog breeds classifier using deep learning built on top of PyTorch.


  The project was build by Stephen Lau (https://stephenllh.github.io).



