title: Dog Breeds Classifier
description: Ever wonder about the breed of the dog you saw on the street? This web app allows you to identify dog breeds using deep learning methods.
about:
  This is a dog breeds classifier using deep learning built on top of PyTorch.



  The project was build by Stephen Lau (https://stephenllh.github.io).

code: https://github.com/stephenllh/web-deep-learning-classifier

sampleImages:
  - name: pembroke
    url: https://i.imgur.com/MMC0Dko.jpeg
  - name: golden retriever
    url: https://i.pinimg.com/236x/aa/4b/db/aa4bdb98313775cee3f8d17afaca7fea.jpg


